allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  unrs-resolver: true

# 自动安装对等依赖
autoInstallPeers: true

minimumReleaseAge: 1
minimumReleaseAgeStrict: true

packages:
  - 'packages/*'
  - 'examples/*'
